services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    env_file:
      - .env
    ports:
      - "3000:3000"
      - "5555:5555"
    volumes:
      - ./src:/usr/src/app/src
      - ./prisma:/usr/src/app/prisma
      - ./logs:/usr/src/app/logs
      - /usr/src/app/node_modules
    command: npm run dev