services:
  # ------------------------------------
  # APPLICATION
  # ------------------------------------
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    restart: always
    env_file:
      - .env

  # ------------------------------------
  # INFRASTRUCTURE (Ports Disabled)
  # ------------------------------------
  db:
    ports: [] # Access only via internal network

  redis:
    ports: [] # Access only via internal network

  minio:
    ports: [] # Access Console/API via internal network (Reverse Proxy)

  mailpit:
    ports: [] # Access UI via internal network (Reverse Proxy)

  waha:
    ports: [] # Access via internal network (Reverse Proxy)
