services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: development # Targets the 'development' stage
    env_file:
      - .env
    ports:
      - "3000:3000"
      - "5555:5555" # Expose Prisma Studio for debugging
    volumes:
      # Sync source code for Hot Reloading
      - ./src:/usr/src/app/src
      # Sync Prisma schema
      - ./prisma:/usr/src/app/prisma
      # Prevent host node_modules from overwriting container modules
      - /usr/src/app/node_modules
    command: npm run dev